const Data = [
    {
        id: "1",
        feature: "first",
        title: "Game Theory for Internet Age",
        link: "https://i.ibb.co/nBWdDQL/ACM-Game-of-theory.jpg",
        descShort: "A 2-Hour Webinar by Dr.R Ramanujam on the topic-Game Theory",
        descLong: "What does a cake have in common with bandwidth? Well, everyone wants as large a piece of it as one can get away with, though we all know we must share. When several people have selfish, potentially conflicting, goals but also must cooperate to achieve something, game theory is the natural realm. Instead of people, consider geographically distributed processes sharing resources across the globe, and you see the connection to computing. In the modern era of computing agents acting autonomously and interacting with each other, strategic reasoning and algorithms combine in new ways, posing new challenges and new opportunities. The talk is an invitation to this fascinating emerging area of research.",
        year: "2020",
        date: "9th June 2020",
    },
    {
        id: "2",
        feature: "second",
        title: "GCC Internal Synopsis",
        link: "https://i.ibb.co/Hd8Phjq/GCC3.jpg",
        descShort: "A 2-Hour Seminar on Introduction to GCC Internal Synopsis by Dr. Abhijat Vichare",
        descLong: "The GNU Compiler Collection is an optimizing, highly portable compiler created by the Free Software Foundation (FSF). Its portability and performance have made it the standard reference compiler against which other compilers are compared with today. Industrially, it has enabled organizations - small and large - to reduce their costs of implementation by simply porting the GCC system to their architecture. Academically, the availability of its source has opened up opportunities for teaching and research using a system used in practice to compile almost every open source, as well as other software out there.This talk introduces the essential architecture of the compiler for anyone interested in porting it for commercial as well as academic goals.",
        year: "2020",
        date: "20th January 2020",
    },
    {
        id: "3",
        feature: "third",
        title: " Automation Industry",
        link: "https://i.ibb.co/fGZHVbG/automation-industry.jpg",
        descShort: "An hour long Webinar on Automation Industry by Mr. Omkar Vichare",
        descLong: "There are automation platforms which allows an entity to automate task just like human beings do across application. This webinar covers various topics which give you a wide overview of automating workflow, processes and interact with website, user portals and application.It also helped develop an overall interest in Automation Industry.",
        year: "2020",
        date: "25th May 2020",
    },
    {
        id: "4",
        feature: "fourth",
        title: "ACM Student Awareness Program",
        link: "https://i.ibb.co/z62zbsc/Aware3.jpg",
        descShort: "An hour long webinar on ACM Student Awareness Program by Dr. M.A.Thalor and Dr. P.B.Mane.",
        descLong: "Organised by AISSMS IOIT ACM student chapter, this event was held online on the CISCO WebEx platform on 5th October 2020. The main objective of this event was to make students aware of the ACM student Chapter in the college and the events held by the chapter. Dr. M.A.Thalor (IT Department HOD) and Dr. P.B.Mane (Principal of AISSMS IOIT) were the speakers of this event.It was a local event which was attended by over 250 participants in the College.The main Points Discussed in this event were:1. Address from Principal sir regarding growth of ACM in college.2. Previous year’s contributions from members and committee.3. Current year’s committee.4. Planned events for upcoming year.5. Benefits of being an ACM member.Program Outcome - The event reached throughout the college's departments. The event was attended by over 250 students from the college. The goals and expectations set for this event were met. The event has opened up a dialogue between the speaker and the participants. This helped build and improve the overall reach of the ACM student chapter.",
        year: "2020",
        date: "5th October 2020",
    },
    {
        id: "5",
        feature: "first",
        title: "Lets Declutter Our Minds",
        link: "https://i.ibb.co/G0VDPLK/Declutter1.jpg",
        descShort: "An hour long webinar on Decluttering our minds by Mrs. Sonali Joshi",
        descLong: "Organized by AISSMS IOIT ACM student Chapter, on 3rd September 2020, this event took place online via the CISCO WebEx platform. The purpose of this event was to help students deal with uncertainties about the future caused by the global pandemic. To help deal with anxiety and stress. To impart motivation. Mrs. Sonali Joshi, a well known Psychologist was the Speaker for this event. It was a local event which was attended by over 150 participants. The event reached nearly 10 colleges in Pune and a couple of colleges outside Pune. The event was attended by over 150 students from these college. The goals and expectations set for this event were met. The event has opened up a dialogue between the speaker and the participants. This helped build and improve the overall reach of the ACM student chapter. ",
        year: "2020",
        date: "3rd September 2020",
    },
    {
        id: "6",
        feature: "second",
        title: "Women Appreciation Week",
        link: "https://i.ibb.co/njpnB41/Women-Appreciation.png",
        descShort: "A week Long program to appreciate Women and have interactive social media competitions",
        descLong: "Organized by AISSMS IOIT ACM student chapter, this event was held online through the social media platform Instagram. This event lasted for 4 Days from 19th October to 22nd October 2020.Interactive Social Media Competitions was the theme of this event. The objective of this event was to celebrate women during Navratri. It also aimed to help increase our social media reach. Held at local level, this event had around 28 participants.The Day wise events conducted in the Women Appreciation Week were - Monday Motivation - The female students conveyed to us how they motivate, pick up themselves in tough times. Tuesday Talk - The students talked about who(woman) and how inspires/inspired them to be better. Women Up - The female students showcased their personal interests. Throwback to the past - We uncovered the work done by women done in history which is unknown to the masses. Outcome of the program -  We achieved to increase our social media reach by 72% in the week through this event as well as collaboration with a college student association (ITSA)",
        year: "2020",
        date: "19th October-22nd October 2020",
    },
    {
        id: "7",
        feature: "third",
        title: "A webinar on Big Data Engineering",
        link: "https://i.ibb.co/kmLbpWt/Big-Data-Engineering.png",
        descLong: "",
        descShort: "A webinar by Mr. Mario Rozario on Big Data Engineering",
        year: "2021",
        date: "28th January 2021",
    },
    {
        id: "8",
        feature: "fourth",
        title: "ACM Awareness Program",
        link: "https://i.ibb.co/25Fhqqn/ACM-Awareness-1.jpg",
        descShort: "An hour long webinar on ACM Student Awareness Program by Dr. M.A.Thalor.",
        descLong: "Organised by AISSMS IOIT ACM student chapter, this event was held online on the CISCO WebEx platform on 5th October 2020. The main objective of this event was to make students aware of the ACM student Chapter in the college and the events held by the chapter. Dr. M.A.Thalor (IT Department HOD) and Dr. P.B.Mane (Principal of AISSMS IOIT) were the speakers of this event.It was a local event which was attended by over 250 participants in the College.The main Points Discussed in this event were:1. Address from Principal sir regarding growth of ACM in college.2. Previous year’s contributions from members and committee.3. Current year’s committee.4. Planned events for upcoming year.5. Benefits of being an ACM member.Program Outcome - The event reached throughout the college's departments. The event was attended by over 250 students from the college. The goals and expectations set for this event were met. The event has opened up a dialogue between the speaker and the participants. This helped build and improve the overall reach of the ACM student chapter.",
        year: "2021",
        date: "9th September 2021",
    },
    {
        id: "9",
        feature: "first",
        title: "Want to Land in your Dream Job",
        link: "https://i.ibb.co/1vJ8hKx/ACM-Webinar1.jpg",
        descShort: "A Webinar by Mr. Rahul Maheshwari on cracking interviews and campus placements.",
        descLong: "",
        year: "2021",
        date: "10th October 2021",
    },
    {
        id: "10",
        feature: "second",
        title: "Ethical Hacking Workshop",
        link: "https://i.ibb.co/NS9dF1F/ACM-EH-Workshop.jpg",
        descShort: "5 day Workshop on Ethical Hacking by AK IT Services Pvt. Ltd.",
        descLong: "",
        year: "2021",
        date: "12th October-16th October 2021",
    },
    {
        id: "11",
        feature: "third",
        title: "Augmented Reality Workshop",
        link: "https://i.ibb.co/0CycW7L/ACM-ARworkshop.jpg",
        descShort: "The objective of this event was to encourage students to buy the ACM membership and spread knowledge about AR.",
        descLong: "The event reached throughout the college's departments. The event was attended by over 130+ students from the college. The goals and expectations set for this event were met. The event has opened up a dialogue between the speaker and the participants. Student have more knowledge about the benefits of the membership. This helped build and improve the overall reach of the ACM student chapter.",
        year: "2022",
        date: "17th January 2022-21th January 2022",
    },
    {
        id: "12",
        feature: "fourth",
        title: "Valorant Mania",
        link: "https://i.ibb.co/ftNCs5k/ACM-valorant.jpg",
        descShort: "The objective of this event was to encourage students to buy the ACM membership and create a fun environment through this event.",
        descLong: "The event reached throughout the college's departments. The event was attended by over 20 students from the college and 5 from outside. The goals and expectations set for this event were met. The event has opened up a dialogue between the speaker and the participants. Student have more knowledge about the benefits of the membership. This helped build and improve the overall reach of the ACM student chapter.",
        year: "2022",
        date: "8th January 2022",
    },
]

export default Data;